-- Postgres-flavored equivalent of migrations/sqlite/20260601000000_blog_init.sql.
-- Runs AFTER arium's migrator() (users, roles, sessions, …) and
-- membership_migrator() (arium_resource_members). author_id / uploaded_by /
-- user_id reference arium's `users.id` (BIGINT in arium's Postgres schema).

-- gen_random_bytes(16) backs the subscriber-token generator in
-- src/db/subscribers.rs (the Postgres analogue of SQLite's randomblob()).
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    slug        TEXT NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS tags (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS posts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              TEXT NOT NULL,
    slug               TEXT NOT NULL UNIQUE,
    body_md            TEXT NOT NULL DEFAULT '',
    body_html          TEXT NOT NULL DEFAULT '',
    excerpt            TEXT NOT NULL DEFAULT '',
    author_id          BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category_id        BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    featured_image_url TEXT,
    status             TEXT NOT NULL DEFAULT 'draft'
                         CHECK (status IN ('draft', 'published', 'archived')),
    published_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_posts_status_published ON posts(status, published_at);
CREATE INDEX IF NOT EXISTS idx_posts_author ON posts(author_id);
CREATE INDEX IF NOT EXISTS idx_posts_category ON posts(category_id);

CREATE TABLE IF NOT EXISTS post_tags (
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    tag_id  BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);
CREATE INDEX IF NOT EXISTS idx_post_tags_tag ON post_tags(tag_id);

CREATE TABLE IF NOT EXISTS comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    author_id   BIGINT REFERENCES users(id) ON DELETE SET NULL,  -- NULL for guests
    guest_name  TEXT,
    guest_email TEXT,
    body        TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_comments_post_status ON comments(post_id, status);
-- Home "recent approved comments" reads filter by status and order by created_at
-- across all posts; idx_comments_post_status is keyed on post_id first and
-- can't serve the post-agnostic recent query.
CREATE INDEX IF NOT EXISTS idx_comments_status_created ON comments(status, created_at);

CREATE TABLE IF NOT EXISTS subscribers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      TEXT NOT NULL UNIQUE,
    confirmed  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Double opt-in confirmation tokens. A fresh subscribe replaces any pending
-- token for that subscriber; confirming consumes (deletes) the row.
CREATE TABLE IF NOT EXISTS subscriber_tokens (
    token         TEXT PRIMARY KEY,
    subscriber_id BIGINT NOT NULL REFERENCES subscribers(id) ON DELETE CASCADE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_subscriber_tokens_subscriber
    ON subscriber_tokens(subscriber_id);

CREATE TABLE IF NOT EXISTS media (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename    TEXT NOT NULL,
    url         TEXT NOT NULL,
    uploaded_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Resized, modern-format renditions of an uploaded image (WordPress-style:
-- thumb/small/medium/large + a full-size re-encode), generated on upload. The
-- original file stays the canonical `media.url`; these are the responsive
-- `srcset` sources. `label` is the size bucket, `format` the codec (webp/avif),
-- and (width,height) the pixel dimensions for that rendition. Rows cascade with
-- the parent media row; the files on disk are unlinked separately on delete.
CREATE TABLE IF NOT EXISTS media_variants (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id   BIGINT NOT NULL REFERENCES media(id) ON DELETE CASCADE,
    label      TEXT NOT NULL,
    format     TEXT NOT NULL,
    width      INTEGER NOT NULL,
    height     INTEGER NOT NULL,
    url        TEXT NOT NULL,
    bytes      BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_media_variants_media ON media_variants(media_id);

CREATE TABLE IF NOT EXISTS post_views (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id      BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    viewed_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    referrer     TEXT,
    visitor_hash TEXT
);
CREATE INDEX IF NOT EXISTS idx_post_views_post ON post_views(post_id);
-- The per-view 24h dedup probe in analytics::record_view filters on
-- (post_id, visitor_hash, viewed_at); this composite lets it seek instead of
-- scanning a post's whole view history on every page view.
CREATE INDEX IF NOT EXISTS idx_post_views_dedup
    ON post_views(post_id, visitor_hash, viewed_at);
-- views-over-time filters by viewed_at alone across all posts.
CREATE INDEX IF NOT EXISTS idx_post_views_viewed_at ON post_views(viewed_at);

-- Anonymous reactions/claps. Like post_views, rows are append-only and keyed by
-- the coarse visitor_hash (analytics::visitor_hash) — no account required. Each
-- row is one clap; reactions::add_reaction caps per-visitor totals and bursts.
CREATE TABLE IF NOT EXISTS reactions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id      BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    kind         TEXT NOT NULL DEFAULT 'clap',
    visitor_hash TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_reactions_post ON reactions(post_id);
-- add_reaction's per-visitor cap + burst probes filter on
-- (post_id, visitor_hash, created_at); this composite lets them seek.
CREATE INDEX IF NOT EXISTS idx_reactions_dedup
    ON reactions(post_id, visitor_hash, created_at);

-- Blog-specific profile fields (arium's users already has display_name/avatar_url).
CREATE TABLE IF NOT EXISTS user_profiles (
    user_id      BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    bio          TEXT,
    social_links TEXT  -- JSON
);

-- Site-wide key/value settings (e.g. `theme_hue` for the Tailwind brand accent).
CREATE TABLE IF NOT EXISTS site_settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Full-text search. The SQLite path uses an FTS5 virtual table with content-sync
-- triggers; Postgres keeps a tsvector column on `posts` itself, fed by a BEFORE
-- trigger that runs on INSERT and on UPDATE-of-title-or-body_md. GIN backs `@@`
-- queries; ts_rank handles ordering. Read-side wiring lives in src/db/posts.rs.
ALTER TABLE posts ADD COLUMN IF NOT EXISTS search_tsv tsvector;
CREATE INDEX IF NOT EXISTS posts_search_tsv_idx ON posts USING gin(search_tsv);

CREATE OR REPLACE FUNCTION posts_search_tsv_update() RETURNS trigger AS $$
BEGIN
    NEW.search_tsv :=
        setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(NEW.body_md, '')), 'B');
    RETURN NEW;
END $$ LANGUAGE plpgsql;

-- Postgres has no CREATE TRIGGER IF NOT EXISTS pre-14; drop-then-create is the
-- portable idempotent form for re-running this migration.
DROP TRIGGER IF EXISTS posts_search_tsv_trg ON posts;
CREATE TRIGGER posts_search_tsv_trg
    BEFORE INSERT OR UPDATE OF title, body_md ON posts
    FOR EACH ROW EXECUTE FUNCTION posts_search_tsv_update();
