// AUTOGENERATED Components module — `dx components add` rewrites this list.
// When re-running it, re-add the project-local entries below by hand.
pub mod avatar;
pub mod button;
pub mod dropdown_menu;
pub mod input;
pub mod navbar;
pub mod select;
pub mod textarea;

// Project-local primitives (not from the catalog).
pub mod alert_dialog;
pub mod surface;
pub mod text;
